
const raagData = [
    { name: "ਆਸਾ", ang: 8, slug: "asa", hasSections: true },
    { name: "ਗੂਜਰੀ", ang: 10, slug: "gujari", hasSections: true },
    { name: "ਗਉੜੀ ਦੀਪਕੀ", ang: 12, slug: null, hasSections: false },
    { name: "ਧਨਾਸਰੀ", ang: 13, slug: "dhanasri", hasSections: true },
    { name: "ਗਉੜੀ ਪੂਰਬੀ", ang: 13, slug: null, hasSections: false },
    { name: "ਸਿਰੀ ਰਾਗੁ", ang: 14, slug: "sri-raag", hasSections: true },
    { name: "ਮਾਝ", ang: 94, slug: "maajh", hasSections: true },
    { name: "ਗਉੜੀ ਗੁਆਰੇਰੀ", ang: 151, slug: null, hasSections: false },
    { name: "ਗਉੜੀ", ang: 151, slug: "gauri", hasSections: true },
    { name: "ਗਉੜੀ ਦਖਣੀ", ang: 152, slug: null, hasSections: false },
    { name: "ਗਉੜੀ ਚੇਤੀ", ang: 154, slug: null, hasSections: false },
    { name: "ਗਉੜੀ ਬੈਰਾਗਣਿ", ang: 155, slug: null, hasSections: false },
    { name: "ਗਉੜੀ ਪੂਰਬੀ ਦੀਪਕੀ", ang: 157, slug: null, hasSections: false },
    { name: "ਗਉੜੀ ਮਾਝ", ang: 172, slug: null, hasSections: false },
    { name: "ਗੌੜੀ ਮਾਲਵਾ", ang: 214, slug: null, hasSections: false },
    { name: "ਗਉੜੀ ਮਾਲਾ", ang: 214, slug: null, hasSections: false },
    { name: "ਗਉੜੀ ਸੋਰਠਿ", ang: 330, slug: null, hasSections: false },
    { name: "ਆਸਾ ਕਾਫੀ", ang: 365, slug: null, hasSections: false },
    { name: "ਆਸਾਵਰੀ", ang: 369, slug: null, hasSections: false },
    { name: "ਆਸਾ ਆਸਾਵਰੀ", ang: 409, slug: null, hasSections: false },
    { name: "ਦੇਵਗੰਧਾਰੀ", ang: 527, slug: "devgandhari", hasSections: true },
    { name: "ਬਿਹਾਗੜਾ", ang: 537, slug: "bihagara", hasSections: true },
    { name: "ਵਡਹੰਸੁ", ang: 557, slug: "wadahans", hasSections: true },
    { name: "ਵਡਹੰਸੁ ਦਖਣੀ", ang: 580, slug: null, hasSections: false },
    { name: "ਸੋਰਠਿ", ang: 595, slug: null, hasSections: false },
    { name: "ਜੈਤਸਰੀ", ang: 696, slug: "jaitsri", hasSections: true },
    { name: "ਟੋਡੀ", ang: 711, slug: "todi", hasSections: true },
    { name: "ਬੈਰਾੜੀ", ang: 719, slug: "bairari", hasSections: true },
    { name: "ਤਿਲੰਗ", ang: 721, slug: "tilang", hasSections: true },
    { name: "ਤਿਲੰਗ ਕਾਫੀ", ang: 726, slug: null, hasSections: false },
    { name: "ਸੂਹੀ", ang: 728, slug: "suhi", hasSections: true },
    { name: "ਸੂਹੀ ਕਾਫੀ", ang: 751, slug: null, hasSections: false },
    { name: "ਸੂਹੀ ਲਲਿਤ", ang: 793, slug: null, hasSections: false },
    { name: "ਬਿਲਾਵਲ", ang: 795, slug: "bilaval", hasSections: true },
    { name: "ਬਿਲਾਵਲ ਦਖਣੀ", ang: 843, slug: null, hasSections: false },
    { name: "ਗੋਂਡ", ang: 859, slug: "gaund", hasSections: true },
    { name: "ਬਿਲਾਵਲ ਗੋਂਡ", ang: 874, slug: null, hasSections: false },
    { name: "ਰਾਮਕਲੀ", ang: 876, slug: "ramkali", hasSections: true },
    { name: "ਰਾਮਕਲੀ ਦਖਣੀ", ang: 907, slug: null, hasSections: false },
    { name: "ਨਟ ਨਾਰਾਇਨ", ang: 975, slug: "nat-narayan", hasSections: true },
    { name: "ਨਟ", ang: 975, slug: null, hasSections: false },
    { name: "ਮਾਲੀ ਗਉੜਾ", ang: 984, slug: "mali-gaura", hasSections: true },
    { name: "ਮਾਰੂ", ang: 989, slug: "maru", hasSections: true },
    { name: "ਮਾਰੂ ਕਾਫੀ", ang: 1014, slug: null, hasSections: false },
    { name: "ਮਾਰੂ ਦਖਣੀ", ang: 1033, slug: null, hasSections: false },
    { name: "ਤੁਖਾਰੀ", ang: 1107, slug: "tukhari", hasSections: true },
    { name: "ਕੇਦਾਰਾ", ang: 1118, slug: "kedara", hasSections: true },
    { name: "ਭੈਰੌ", ang: 1125, slug: "bhairau", hasSections: true },
    { name: "ਬਸੰਤੁ", ang: 1168, slug: "basant", hasSections: true },
    { name: "ਬਸੰਤੁ ਹਿੰਡੋਲ", ang: 1170, slug: null, hasSections: false },
    { name: "ਸਾਰੰਗ", ang: 1197, slug: "sarang", hasSections: true },
    { name: "ਮਲਾਰ", ang: 1254, slug: "malaar", hasSections: true },
    { name: "ਕਾਨੜਾ", ang: 1294, slug: "kanara", hasSections: true },
    { name: "ਕਲਿਆਨ", ang: 1319, slug: "kalyan", hasSections: true },
    { name: "ਕਲਿਆਨ ਭੋਪਾਲੀ", ang: 1321, slug: null, hasSections: false },
    { name: "ਪ੍ਰਭਾਤੀ ਬਿਭਾਸ", ang: 1327, slug: null, hasSections: false },
    { name: "ਪ੍ਰਭਾਤੀ", ang: 1327, slug: "prabhati", hasSections: true },
    { name: "ਪ੍ਰਭਾਤੀ ਦਖਣੀ", ang: 1344, slug: null, hasSections: false },
    { name: "ਬਿਭਾਸ ਪ੍ਰਭਾਤੀ", ang: 1347, slug: null, hasSections: false },
    { name: "ਜੈਜਾਵੰਤੀ", ang: 1352, slug: "jaijavanti", hasSections: true },
];

export default raagData;